[package]
name = "miagobble/praxis"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
homepage = "https://praxis.igottic.com/"
description = "Library with utilities and more for general usage in any project."

[dependencies]
Badges = "miagobble/badges@1.0.1"
Bezier = "miagobble/bezier@1.1.0"
Binder = "miagobble/binder@1.0.0"
Bucket = "miagobble/bucket@1.0.5"
Child = "miagobble/child@1.0.0"
DataStore = "miagobble/data-store@1.0.1"
DialogueTree = "miagobble/dialogue-tree@1.0.0"
EffectPlayer = "miagobble/effect-player@1.0.0"
Initializer = "miagobble/initializer@1.0.0"
Input = "miagobble/input@1.0.2"
Oklab = "miagobble/oklab@1.0.0"
Optional = "miagobble/optional@1.0.0"
ProgressionUtils = "miagobble/progression-utils@1.0.4"
RateLimiter = "miagobble/rate-limiter@1.0.0"
SeamStoryUtils = "miagobble/seam-story-utils@0.1.3"
SerDes = "miagobble/ser-des@1.0.0"
Signal = "miagobble/signal@1.0.1"
Symbol = "miagobble/symbol@1.0.2"
TagUtils = "miagobble/tag-utils@1.0.1"
Time = "miagobble/time@1.0.0"
TracebackUtils = "miagobble/traceback-utils@1.0.1"
Typer = "miagobble/typer@0.1.1"
ValuePacker = "miagobble/value-packer@1.0.0"
