name = "miagobble/effect_player"
version = "1.0.0"
description = "Play visual effects created by standard visual effect plugins."
license = "MIT"
authors = ["Mia Gobble (https://praxis.igottic.com/)"]
repository = "https://github.com/MiaGobble/Praxis"

includes = ["pesde.toml", "init.luau"]

[target]
environment = "roblox"
lib = "init.luau"
build_files = ["init.luau"]

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
Bezier = { workspace = "miagobble/bezier", version = "^" }
