[package]
name = "miagobble/data-store"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
homepage = "https://praxis.igottic.com/"
description = "Wrapper utilities around Roblox DataStoreService with retry support and ser/des for any type."

[dependencies]
