[package]
name = "miagobble/bezier"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
homepage = "https://praxis.igottic.com/"
description = "A utility module for working with Bezier curves."

[dependencies]
