[package]
name = "miagobble/tag-utils"
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
homepage = "https://praxis.igottic.com/"
description = "Wrapper for collection service to make it easier to work with tags."

[dependencies]
