[package]
name = "miagobble/time"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
homepage = "https://praxis.igottic.com/"
description = "Utilities related to time, including for daily rewards."

[dependencies]