[package]
name = "miagobble/oklab"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
homepage = "https://praxis.igottic.com/"
description = "A different color space that looks more uniform to the human eye."

[dependencies]
