-- Author: @iGottic (Mia Gobble)
-- See more info here: https://github.com/MiaGobble/Praxis

local Praxis = {}

-- Imports
local Packages = script.Packages

Praxis.Seam = require(Packages.Seam)
Praxis.Heap = require(Packages.Heap)
Praxis.Symbol = require(Packages.Symbol)
Praxis.Typer = require(Packages.Typer)
Praxis.Epoxyish = require(Packages.Epoxyish)
Praxis.TracebackUtils = require(Packages.TracebackUtils)

return Praxis