[package]
name = "miagobble/praxis"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
homepage = "https://praxis.igottic.com/"
description = "Library with utilities and more for general usage in any project."

[dependencies]
